version: '3.8'

x-mautic-volumes:
  &mautic-volumes
  - mautic-html-config:/var/www/html/config
  - mautic-html-logs:/var/www/html/var/logs
  - mautic-media-files:/var/www/html/docroot/media/files
  - mautic-media-images:/var/www/html/docroot/media/images
  - mautic-cron:/opt/mautic/cron

services:
  mautic-mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=mautic
      - MYSQL_USER=mautic
      - MYSQL_PASSWORD=mauticpwd
    volumes:
      - mautic-mysql-data:/var/lib/mysql
    healthcheck:
      test: mysqladmin --user=mautic --password=mauticpwd ping
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - traefik-net

  mautic-rabbitmq:
    image: rabbitmq:3
    restart: always
    environment:
      - RABBITMQ_DEFAULT_VHOST=mautic
    volumes:
      - mautic-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - traefik-net

  mautic-web:
    image: mautic/mautic:5-apache
    restart: always
    volumes: *mautic-volumes
    environment:
      - DOCKER_MAUTIC_LOAD_TEST_DATA=false
      - DOCKER_MAUTIC_RUN_MIGRATIONS=false

      - MAUTIC_DB_HOST=mautic-mysql
      - MAUTIC_DB_PORT=3306
      - MAUTIC_DB_DATABASE=mautic
      - MAUTIC_DB_USER=mautic
      - MAUTIC_DB_PASSWORD=mauticpwd
      - PHP_INI_VALUE_DATE_TIMEZONE=America/Sao_Paulo

      - MAUTIC_MESSENGER_DSN_EMAIL=amqp://guest:guest@mautic-rabbitmq:5672/mautic/messages
      - MAUTIC_MESSENGER_DSN_HIT=amqp://guest:guest@mautic-rabbitmq:5672/mautic/messages
    healthcheck:
      test: curl http://localhost
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 100
    depends_on:
      mautic-mysql:
        condition: service_healthy
    networks:
      - traefik-net
    labels:
      - traefik.enable=true      
      - traefik.http.routers.botapp.rule=Host(`mautic.localhost`)
      - traefik.http.routers.botapp.entrypoints=web #websecure
      # - traefik.http.routers.botapp.tls.certresolver=letsencrypt-resolver      

  mautic-cron:
    image: mautic/mautic:5-apache
    restart: always
    volumes: *mautic-volumes
    environment:
      - DOCKER_MAUTIC_ROLE=mautic_cron

      - MAUTIC_DB_HOST=mautic-mysql
      - MAUTIC_DB_PORT=3306
      - MAUTIC_DB_DATABASE=mautic
      - MAUTIC_DB_USER=mautic
      - MAUTIC_DB_PASSWORD=mauticpwd
      - PHP_INI_VALUE_DATE_TIMEZONE=America/Sao_Paulo

      - MAUTIC_MESSENGER_DSN_EMAIL=amqp://guest:guest@mautic-rabbitmq:5672/mautic/messages
      - MAUTIC_MESSENGER_DSN_HIT=amqp://guest:guest@mautic-rabbitmq:5672/mautic/messages
    depends_on:
      mautic-web:
        condition: service_healthy
    networks:
      - traefik-net

  mautic-worker:
    image: mautic/mautic:5-apache
    restart: always
    volumes: *mautic-volumes
    environment:
      - DOCKER_MAUTIC_ROLE=mautic_worker

      - MAUTIC_DB_HOST=mautic-mysql
      - MAUTIC_DB_PORT=3306
      - MAUTIC_DB_DATABASE=mautic
      - MAUTIC_DB_USER=mautic
      - MAUTIC_DB_PASSWORD=mauticpwd
      - PHP_INI_VALUE_DATE_TIMEZONE=America/Sao_Paulo

      - MAUTIC_MESSENGER_DSN_EMAIL=amqp://guest:guest@mautic-rabbitmq:5672/mautic/messages
      - MAUTIC_MESSENGER_DSN_HIT=amqp://guest:guest@mautic-rabbitmq:5672/mautic/messages
    depends_on:
      mautic-web:
        condition: service_healthy
    networks:
      - traefik-net

volumes:
  mautic-html-config:
  mautic-html-logs:
  mautic-media-files:
  mautic-media-images:
  mautic-cron:
  mautic-mysql-data:
  mautic-rabbitmq-data:

networks:
  traefik-net:
    external: true