version: '3.8'

services:

  qdrant:
    image: qdrant/qdrant
    restart: unless-stopped
    networks:
      - traefik-net
    ports:
      - 6333:6333
    environment:
      - QDRANT__SERVICE__API_KEY=93c193d2-5b52-4cd4-9e2c-b080937b79W4
    volumes:
      - qdrant-data:/qdrant/storage
    labels:
      - traefik.enable=true
      - traefik.http.routers.qdrant.rule=Host(`qdrant.localhost`)
      - traefik.http.routers.qdrant.entrypoints=web # ,websecure
      - traefik.http.services.qdrant.loadbalancer.server.port=6333
      # - traefik.http.routers.qdrant.tls.certresolver=letsencrypt-resolver

volumes:
  qdrant-data:
    name: qdrant-data

networks:
  traefik-net:
    external: true