version: '3.8'

services:
  db-postgres:
    image: postgres
    restart: unless-stopped
    networks:
      - traefik-net
    volumes:
      - db-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=meubanco
      - POSTGRES_USER=meuusuario
      - POSTGRES_PASSWORD=minhasenha
    healthcheck: 
      test: "pg_isready -U postgres -d postgres"
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  db-postgres-data:
    name: db-postgres-data

networks:
  traefik-net:
    external: true