version: "3.8"

services:
  langflow-db:
    image: postgres
    restart: always
    networks:
      - traefik-net
    volumes:
      - langflow-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: langflow
      POSTGRES_PASSWORD: 123456
      
  langflow:
    image: langflowai/langflow:latest
    restart: always
    pull_policy: always
    networks:
      - traefik-net
    depends_on:
      - langflow-db
    volumes:
      - langflow-data:/var/lib/langflow
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://postgres:123456@langflow-db:5432/langflow

      - LANGFLOW_SUPERUSER=admin
      - LANGFLOW_SUPERUSER_PASSWORD=123456
      - LANGFLOW_SECRET_KEY=@#$%^&*
      - LANGFLOW_NEW_USER_IS_ACTIVE=False
      - LANGFLOW_AUTO_LOGIN=False
    labels:
      - traefik.enable=true
      - traefik.http.routers.langflow.rule=Host(`langflow.localhost`)
      - traefik.http.routers.langflow.entrypoints=web,websecure
      - traefik.http.services.langflow.loadbalancer.server.port=7860
      # - traefik.http.routers.langflow.tls.certresolver=letsencrypt-resolver

volumes:
  langflow-db-data:
    name: langflow-db-data
  langflow-data:
    name: langflow-data

networks:
  traefik-net:
    external: true