# https://raw.githubusercontent.com/kestra-io/kestra/develop/docker-compose.yml

x-shared-env: &shared-env
  KESTRA_CONFIGURATION: |
    kestra:
      tutorialFlows:
        enabled: false
      repository:
        type: postgres
      queue:
        type: postgres
      storage:
        type: local
        local:
          basePath: "/app/storage"
      tasks:
        tmp-dir:
          path: /tmp/kestra-wd/tmp
      url: http://kestra.localhost/
    datasources:
      postgres:
        url: jdbc:postgresql://kestra-postgres:5432/kestra
        driverClassName: org.postgresql.Driver
        username: kestra
        password: k3str4

services:

  kestra-postgres:
    image: postgres:18
    restart: unless-stopped
    networks:
      - traefik-net
    volumes:
      - kestra-postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      start_period: 5s
      interval: 30s
      timeout: 10s
      retries: 10

  kestra:
    image: kestra/kestra:latest
    user: "root"
    command: server standalone
    stop_grace_period: 6m
    restart: unless-stopped
    networks:
      - traefik-net
    volumes:
      - kestra-data:/app/storage
      - /tmp/kestra-wd:/tmp/kestra-wd
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      <<: *shared-env
    depends_on:
      kestra-postgres:
        condition: service_started
    labels:
      - traefik.enable=true
      - traefik.http.routers.kestra.rule=Host(`kestra.localhost`)
      - traefik.http.routers.kestra.entrypoints=web
      - traefik.http.services.kestra.loadbalancer.server.port=8080

volumes:
  kestra-postgres-data:
    driver: local
  kestra-data:
    driver: local

networks:
  traefik-net:
    external: true