services:
  traefik:
    image: traefik
    restart: unless-stopped
    networks:
      - traefik-net        
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --api.dashboard=true

      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443

      - --log.level=INFO

      # - --entrypoints.web.http.redirections.entryPoint.to=websecure
      # - --entrypoints.web.http.redirections.entryPoint.scheme=https

      # - --certificatesresolvers.letsencrypt-resolver.acme.email=afonsoaaf@gmail.com
      # - --certificatesresolvers.letsencrypt-resolver.acme.storage=/traefik/files/acme.json
      # - --certificatesresolvers.letsencrypt-resolver.acme.tlschallenge=true
      # - --certificatesresolvers.letsencrypt-resolver.acme.dnschallenge=true
      # - --certificatesresolvers.letsencrypt-resolver.acme.dnschallenge.provider=cloudflare
      # - --certificatesresolvers.letsencrypt-resolver.acme.dnschallenge.delaybeforecheck=0
      
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-data:/traefik/files
    # environment:
    #   - CLOUDFLARE_DNS_API_TOKEN=xxx
    #   - CLOUDFLARE_ZONE_API_TOKEN=xxx
    #   - CLOUDFLARE_EMAIL=afonsoaaf@gmail.com
    #   - CLOUDFLARE_API_KEY=xxx
    labels:
      - traefik.enable=true
      
      - traefik.http.routers.traefik.service=api@internal

      - traefik.http.routers.traefik.middlewares=traefik-auth
      - traefik.http.middlewares.traefik-auth.basicauth.users=traefik:$$1$$zDADkWNL$$avhsuZGfDitP1JFCoagVd0

      - traefik.http.routers.traefik.rule=Host(`traefik.localhost`)
      - traefik.http.routers.traefik.entrypoints=web # ,websecure

      # - traefik.http.routers.traefik.tls.certresolver=letsencrypt-resolver

  portainer:
    image: portainer/portainer-ce
    restart: unless-stopped
    networks:
      - traefik-net 
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    labels:
      - traefik.enable=true
      
      - traefik.http.routers.portainer.rule=Host(`portainer.localhost`)
      - traefik.http.routers.portainer.entrypoints=web # ,websecure
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      
      # - traefik.http.routers.portainer.tls.certresolver=letsencrypt-resolver

volumes:
  traefik-data:
    name: traefik-data
  portainer-data:
    name: portainer-data

networks:
  traefik-net:
    name: traefik-net