version: '3.8'

services:

  qdrant:
    image: qdrant/qdrant
    restart: always
    networks:
      - traefik-net
    ports:
      - 6333:6333
    environment:
      - QDRANT__SERVICE__API_KEY=93c193d2-5b52-4cd4-9e2c-b080937b79W4
    volumes:
      - qdrant-data:/qdrant/storage

volumes:
  qdrant-data:
    name: qdrant-data

networks:
  traefik-net:
    external: true