# https://github.com/calcom/docker/

# Não chegou a funcionar. Internamente, o sistema tenta acessar localhost:5555, mas não há esse serviço.
# Imagino que seria a api v2, mas ainda assim, não sei o que fazer para solucionar.

version: '3.8'

services:
  calcom-db:
    image: postgres
    restart: always
    volumes:
      - calcom-db-data:/var/lib/postgresql/data/
    networks:
      - traefik-net
    environment:
      - POSTGRES_DB=calcom
      - POSTGRES_PASSWORD=calcom

  calcom:
    image: calcom/cal.com
    restart: always
    depends_on:
      - calcom-db
    networks:
      - traefik-net
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_LICENSE_CONSENT=true
      - LICENSE=agree

      - CALENDSO_ENCRYPTION_KEY=${CALENDSO_ENCRYPTION_KEY}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=calcom
      - POSTGRES_DB=calcom
      - DATABASE_HOST=calcom-db:5432
      - DATABASE_URL=postgresql://postgres:calcom@calcom-db:5432/calcom
      - DATABASE_DIRECT_URL=postgresql://postgres:calcom@calcom-db:5432/calcom

      - NEXT_PUBLIC_WEBAPP_URL=https://calcom.alexandreafonso.com.br
      - NEXTAUTH_URL=https://calcom.alexandreafonso.com.br
      - NEXT_PUBLIC_API_V2_URL=https://calcom.alexandreafonso.com.br/api/v2

      - NEXT_PUBLIC_APP_NAME="Cal.com"
      - NEXT_PUBLIC_SUPPORT_MAIL_ADDRESS="contato@alexandreafonso.com.br"
      - NEXT_PUBLIC_COMPANY_NAME="Assessoria de Marketing"
      - NEXT_PUBLIC_DISABLE_SIGNUP=false

      - EMAIL_FROM=contato@alexandreafonso.com.br
      - EMAIL_SERVER_HOST=smtp.sendgrid.net
      - EMAIL_SERVER_PORT=465
      - EMAIL_SERVER_USER=apikey
      - EMAIL_SERVER_PASSWORD=${SENDGRID_API_KEY}

      - GOOGLE_API_CREDENTIALS=${GOOGLE_API_CREDENTIALS}
    labels:
      - traefik.enable=true
      - traefik.http.routers.calcom.rule=Host(`calcom.alexandreafonso.com.br`)
      - traefik.http.routers.calcom.entrypoints=web,websecure
      - traefik.http.services.calcom.loadbalancer.server.port=3000
      - traefik.http.routers.calcom.tls.certresolver=letsencrypt-resolver


volumes:
  calcom-db-data:
    name: calcom-db-data

networks:
  traefik-net:
    external: true