version: "3.3"

services:
  traefik:
    image: traefik
    container_name: traefik
    networks:
      - traefik-net        
    restart: always
    command:
      - --providers.docker=true
      - --api.insecure=true
      - --api.dashboard=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --log.level=ERROR
      # - --certificatesresolvers.letsencrypt-resolver.acme.email=afonsoaaf@gmail.com
      # - --certificatesresolvers.letsencrypt-resolver.acme.tlschallenge=true
      # - --certificatesresolvers.letsencrypt-resolver.acme.httpchallenge=true
      # - --certificatesresolvers.letsencrypt-resolver.acme.httpchallenge.entrypoint=web
      # - --certificatesresolvers.letsencrypt-resolver.acme.storage=/traefik/files/acme.json
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-files:/traefik/files
    labels:
      - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
      # - traefik.http.routers.http-catchall.entrypoints=websecure
      - traefik.http.routers.http-catchall.entrypoints=web
      # - traefik.http.routers.http-catchall.middlewares=redirect-to-https
      # - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.traefik-dashboard.rule=Host(`traefik.localhost`)
      # - traefik.http.routers.traefik-dashboard.entrypoints=websecure
      - traefik.http.routers.traefik-dashboard.entrypoints=web
      # - traefik.http.routers.traefik-dashboard.tls.certresolver=letsencrypt-resolver
      - traefik.http.routers.traefik-dashboard.service=api@internal
      - traefik.http.middlewares.traefik-auth.basicauth.users=traefik:$2y$10$3M346AmM3THPammcuvWY1OmTWkv342wQT62rVuJHAMU.AOV05lMMC # Tr@3f1kW3b23Ve!
      - traefik.http.routers.traefik-dashboard.middlewares=traefik-auth

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    networks:
      - traefik-net 
    restart: always
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    labels:
      - traefik.enable=true
      
      # Frontend
      - traefik.http.routers.portainer-frontend.rule=Host(`portainer.localhost`)
      # - traefik.http.routers.portainer-frontend.entrypoints=websecure
      - traefik.http.routers.portainer-frontend.entrypoints=web
      # - traefik.http.routers.portainer-frontend.tls.certresolver=letsencrypt-resolver
      - traefik.http.services.portainer-frontend.loadbalancer.server.port=9000
      - traefik.http.routers.portainer-frontend.service=portainer-frontend

volumes:
  traefik-files:
    name: traefik-files
  portainer-data:
    name: portainer-data

networks:
  traefik-net:
    name: traefik-net