version: "3.3"

services:
  traefik:
    image: traefik
    container_name: traefik
    networks:
      - traefik-net        
    restart: always
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --api.dashboard=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --log.level=ERROR

      # - --certificatesresolvers.letsencrypt-resolver.acme.email=afonsoaaf@gmail.com
      # - --certificatesresolvers.letsencrypt-resolver.acme.storage=/traefik/files/acme.json
      # - --certificatesresolvers.letsencrypt-resolver.acme.tlschallenge=true

      # - --entrypoints.web.http.redirections.entryPoint.to=websecure
      # - --entrypoints.web.http.redirections.entryPoint.scheme=https
      
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-data:/traefik/files
    labels:
      - traefik.enable=true
      
      - traefik.http.routers.traefik.service=api@internal

      - traefik.http.routers.traefik.middlewares=traefik-auth
      - traefik.http.middlewares.traefik-auth.basicauth.users=traefik:e10adc3949ba59abbe56e057f20f883e

      - traefik.http.routers.traefik.rule=Host(`traefik.localhost`)
      - traefik.http.routers.traefik.entrypoints=web,websecure

      # - traefik.http.routers.traefik.tls.certresolver=letsencrypt-resolver

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    networks:
      - traefik-net 
    restart: always
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    labels:
      - traefik.enable=true
      
      - traefik.http.routers.portainer.rule=Host(`portainer.localhost`)
      - traefik.http.routers.portainer.entrypoints=web,websecure
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      
      # - traefik.http.routers.portainer.tls.certresolver=letsencrypt-resolver

volumes:
  traefik-data:
    name: traefik-data
  portainer-data:
    name: portainer-data

networks:
  traefik-net:
    name: traefik-net