version: '3.3'

services:
    
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    networks:
      - traefik-net
    environment:
      - PGADMIN_DEFAULT_EMAIL=afonsoaaf@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    labels:
      - traefik.enable=true
      - traefik.http.routers.pgadmin.rule=Host(`pgadmin.localhost`)
      - traefik.http.routers.pgadmin.entrypoints=web,websecure
      - traefik.http.services.pgadmin.loadbalancer.server.port=80
      - traefik.http.services.pgadmin.loadbalancer.passHostHeader=true
      # - traefik.http.routers.pgadmin.tls.certresolver=letsencrypt-resolver
    
volumes:
  pgadmin-data:
    name: pgadmin-data

networks:
  traefik-net:
    external: true