version: '3.8'

services:
  db-postgres:
    image: postgres
    restart: always
    networks:
      - traefik-net
    volumes:
      - db-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=meubanco
      - POSTGRES_USER=meuusuario
      - POSTGRES_PASSWORD=minhasenha
    healthcheck: 
      interval: 10s
      retries: 10
      test: "pg_isready -U postgres -d postgres"
      timeout: 5s

volumes:
  db-postgres-data:
    name: db-postgres-data

networks:
  traefik-net:
    external: true