version: '3.3'

x-shared-env: &shared-env
  LOG_LEVEL: INFO
  SECRET_KEY: ${DIFY_SECRET_KEY}
  CONSOLE_WEB_URL: 
  INIT_PASSWORD: 
  CONSOLE_API_URL: 
  SERVICE_API_URL: 
  FILES_URL: 
  APP_WEB_URL: http://dify.localhost

  WEB_API_CORS_ALLOW_ORIGINS: '*'
  CONSOLE_CORS_ALLOW_ORIGINS: '*'

  CODE_EXECUTION_ENDPOINT: http://dify-sandbox:8194
  CODE_EXECUTION_API_KEY: ${DIFY_SANDBOX_API_KEY}
  CODE_MAX_NUMBER: 9223372036854775807
  CODE_MIN_NUMBER: -9223372036854775808
  CODE_MAX_STRING_LENGTH: 80000
  TEMPLATE_TRANSFORM_MAX_LENGTH: 80000
  CODE_MAX_STRING_ARRAY_LENGTH: 30
  CODE_MAX_OBJECT_ARRAY_LENGTH: 30
  CODE_MAX_NUMBER_ARRAY_LENGTH: 1000

  MIGRATION_ENABLED: true
  
  DB_USERNAME: postgres
  DB_PASSWORD: 123456
  DB_HOST: dify-db
  DB_PORT: 5432
  DB_DATABASE: dify

  REDIS_HOST: dify-db-kv
  REDIS_PORT: 6379
  REDIS_USE_SSL: false
  REDIS_DB: 0
  REDIS_USERNAME:
  REDIS_PASSWORD:

  CELERY_BROKER_URL: redis://dify-db-kv:6379/1

  # STORAGE_TYPE: local
  # STORAGE_LOCAL_PATH: storage

  STORAGE_TYPE: s3

  S3_ENDPOINT: ${R2_AWS_S3_ENDPOINT}
  S3_BUCKET_NAME: dify
  S3_ACCESS_KEY: ${R2_AWS_S3_ACCESS_KEY}
  S3_SECRET_KEY: ${R2_AWS_S3_SECRET_KEY}
  S3_REGION: auto

  # VECTOR_STORE: qdrant
  QDRANT_URL: http://qdrant:6333
  QDRANT_API_KEY: difyai123456
  QDRANT_CLIENT_TIMEOUT: 20
  QDRANT_GRPC_ENABLED: false
  QDRANT_GRPC_PORT: 6334

  VECTOR_STORE: weaviate
  WEAVIATE_ENDPOINT: http://dify-weaviate:8080
  WEAVIATE_API_KEY: ${WEAVIATE_API_KEY}
  WEAVIATE_CLIENT_TIMEOUT: 20

  MAIL_TYPE: smtp
  MAIL_DEFAULT_SEND_FROM: "contato@alexandreafonso.com.br eg: no-reply contato@alexandreafonso.com.br)"
  SMTP_SERVER: smtp.gmail.com
  SMTP_PORT: 587
  SMTP_USERNAME: apikey
  SMTP_PASSWORD: ${SENDGRID_API_KEY}

  SENTRY_DSN: 
  SENTRY_TRACES_SAMPLE_RATE: 1.0
  SENTRY_PROFILES_SAMPLE_RATE: 1.0

  EDITION: SELF_HOSTED
  APP_API_URL: http://dify.localhost

services:

  dify-db:
    image: postgres
    restart: always
    networks:
      - traefik-net
    volumes:
      - dify-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dify
      - POSTGRES_PASSWORD=123456

  dify-db-kv:
    image: redis
    restart: always
    networks:
      - traefik-net
    volumes:
      - dify-db-kv-data:/data
    environment:
      - REDIS_HOST=dify-db-kv
      - REDIS_PORT=6379
      - REDIS_USE_SSL=false
      - REDIS_DB=0
      
  dify-api:
    image: langgenius/dify-api:latest
    restart: always
    volumes:
      - dify-data:/app/api/storage
    networks:
      - traefik-net
    environment:
      <<: *shared-env
      MODE: api      

  dify-worker:
    image: langgenius/dify-api:latest
    restart: always
    volumes:
      - dify-data:/app/api/storage
    networks:
      - traefik-net
    environment:
      <<: *shared-env
      MODE: worker
    depends_on:
      - dify-db
      - dify-db-kv

  dify-web:
    image: langgenius/dify-web:latest
    restart: always
    networks:
      - traefik-net
    environment:
      <<: *shared-env

  dify-sandbox:
    image: langgenius/dify-sandbox:latest
    restart: always
    networks:
      - traefik-net    
    environment:
      - API_KEY=${DIFY_SANDBOX_API_KEY}
      - GIN_MODE=release
      - WORKER_TIMEOUT=15

  dify-nginx-files:
    image: bitnami/git
    volumes:
      - ${SYSTEM_FOLDER:-/opt}:/root/files
    command: >
      sh -c "
        if [ ! -d /root/files/dify-service/dify/docker ]; then
          mkdir -p /root/files/dify-service &&
          cd /root/files/dify-service &&
          git clone https://github.com/langgenius/dify.git &&
          sed -i 's|http://api|http://dify-api|g' /root/files/dify-service/dify/docker/nginx/conf.d/default.conf.template &&
          sed -i 's|http://web|http://dify-web|g' /root/files/dify-service/dify/docker/nginx/conf.d/default.conf.template &&
          echo 'Done git clone!'
        else
          echo 'Git clone already got done!'
        fi
      "

  dify-nginx:
    image: nginx:latest
    restart: always
    entrypoint: ["sh", "-c", "chmod +x /docker-entrypoint.sh && /docker-entrypoint.sh"]
    depends_on:
      dify-nginx-files:
        condition: service_completed_successfully
    volumes:
      - ${SYSTEM_FOLDER}/dify-service/dify/docker/nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ${SYSTEM_FOLDER}/dify-service/dify/docker/nginx/proxy.conf.template:/etc/nginx/proxy.conf.template
      - ${SYSTEM_FOLDER}/dify-service/dify/docker/nginx/conf.d:/etc/nginx/conf.d
      - ${SYSTEM_FOLDER}/dify-service/dify/docker/nginx/docker-entrypoint.sh:/docker-entrypoint.sh
      - ${SYSTEM_FOLDER}/dify-service/dify/docker/nginx/ssl:/etc/ssl
    networks:
      - traefik-net
    environment:
      - NGINX_SSL_CERT_FILENAME=dify.crt
      - NGINX_SSL_CERT_KEY_FILENAME=dify.key
      - NGINX_SSL_PROTOCOLS=TLSv1.1 TLSv1.2 TLSv1.3
      - NGINX_WORKER_PROCESSES=auto
      - NGINX_CLIENT_MAX_BODY_SIZE=15M
      - NGINX_KEEPALIVE_TIMEOUT=65
      - NGINX_PROXY_READ_TIMEOUT=3600s
      - NGINX_PROXY_SEND_TIMEOUT=3600s
      - NGINX_SERVER_NAME=_
      - NGINX_PORT=80
    labels:
      - traefik.enable=true
      - traefik.http.routers.dify-nginx.rule=Host(`dify.localhost`)
      - traefik.http.routers.dify-nginx.entrypoints=web,websecure
      - traefik.http.services.dify-nginx.loadbalancer.server.port=80
      - traefik.http.services.dify-nginx.loadbalancer.passHostHeader=true
      # - traefik.http.routers.dify-nginx.tls.certresolver=letsencrypt-resolver

  dify-weaviate:
    image: semitechnologies/weaviate:1.19.0
    restart: always
    volumes:
      - dify-weaviate-data:/var/lib/weaviate
    environment:
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - CLUSTER_HOSTNAME=node1
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=false
      - DEFAULT_VECTORIZER_MODULE=none

      - AUTHENTICATION_APIKEY_ENABLED=true
      - AUTHENTICATION_APIKEY_ALLOWED_KEYS=${WEAVIATE_API_KEY}
      - AUTHENTICATION_APIKEY_USERS=contato@alexandreafonso.com.br
      - AUTHORIZATION_ADMINLIST_ENABLED=true
      - AUTHORIZATION_ADMINLIST_USERS=contato@alexandreafonso.com.br

      - DISABLE_TELEMETRY=true
    networks:
      - traefik-net

volumes:
  dify-data:
    name: dify-data
  dify-weaviate-data:
    name: dify-weaviate-data
  dify-db-data:
    name: dify-db-data
  dify-db-kv-data:
    name: dify-db-kv-data

networks:
  traefik-net:
    external: true