version: '3'

services:
  redis:
    image: redis:latest
    command: ["redis-server", "--requirepass", "kzNnHSZo2WrqT0sN"]
    restart: unless-stopped
    networks:
      - traefik-net
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=kzNnHSZo2WrqT0sN
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "kzNnHSZo2WrqT0sN", "ping"]
      start_period: 10s
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  redis-data:

networks:
  traefik-net:
    external: true