version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak
    networks:
      - traefik-net
    command:
      - start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=123456
    labels:
      - traefik.enable=true
      - traefik.http.routers.keycloak.rule=Host(`keycloak.localhost`)
      - traefik.http.routers.keycloak.entrypoints=web,websecure
      - traefik.http.services.keycloak.loadbalancer.server.port=8080
      # - traefik.http.routers.keycloak.tls.certresolver=letsencrypt-resolver

networks:
  traefik-net:
    external: true