version: '3.8'

services:

  db-mysql:
    image: mysql:5.7
    restart: always
    networks:
      - traefik-net
    volumes:
      - db-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspassword

volumes:
  db-mysql:

networks:
  traefik-net:
    external: true
